version: '3'
services: 
    redis:
        image: redis:4.0.5-alpine
        ports: 
            - 6379:6379
        networks: 
            - servicesnet
        command: ["redis-server", "--appendonly", "yes", "/usr/local/etc/redis/redis.conf"]
        volumes: 
            - redis-data:/data
            - ./dockers/redis/redis.conf:/usr/local/etc/redis/redis.conf
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment: 
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=root
            - HTTP_PASSWORD=qwerty
        ports: 
            - 8081:8081
        depends_on: 
            - redis
    portfolio-api-prod:
        build: 
            context: ./dockers/go/
            target: dev
            container_name: portfolio-api-prod
        volumes: 
            - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
        env_file: 
            - .env
        networks: 
            - servicesnet
        command: dlv debug --accept-multiclient --continue --headless --listen=:2345 --api-version=2 --log ./

volumes: 
    redis-data:

networks: 
    servicesnet:

        
