version: '3'
services: 
    redis:
        image: redis:6.0.7-alpine
        container_name: redis
        build: 
            context: ./dockers/redis/
            dockerfile: Dockerfile
        ports: 
            - "6379:6379"
        networks: 
            - servicesnet
        # command: ["redis-server", "--appendonly", "yes", "/usr/local/etc/redis/redis.conf"]
        # command: ["redis-server", "--appendonly", "yes"]
        volumes: 
            - ./dockers/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - redis-data:/usr/local/etc/redis
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment: 
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=root
            - HTTP_PASSWORD=qwerty
        ports: 
            - "8081:8081"
        networks: 
            - servicesnet
        depends_on: 
            - redis
    # portfolio-api-dev:
    #     build: 
    #         context: ./dockers/go/
    #         target: dev
    #         container_name: portfolio-api-prod
    #         dockerfile: Dockerfile
    #     volumes: 
    #         - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    #     env_file: 
    #         - .env
    #     networks: 
    #         - servicesnet
    #     command: CompileDaemon --build="go build -o main ./" --command=./out

volumes: 
    redis-data:

networks: 
    servicesnet:
